name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00”
  workflow_dispatch: # allows you to trigger manually

jobs:
  build:
    name: python-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: ssh-auth-dev # Defined in ci/environment.yml
          auto-update-conda: false
          python-version: ${{ matrix.python-version }}
          environment-file: ci/environment.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Set up conda environment
        run: |
          python -m pip install -e .
          conda list

      # - name: Run Tests
      #   run: |
      #     python -m pytest -n 4 --cov=./ --cov-report=xml --verbose
